[package]
name = "logv"
version = "0.1.0"
authors = ["Ildar Faizov <ildar.faizov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "*"
cursive = "*"
clap = "~2.33"
crossbeam-channel = "0.5.1"
uuid = { version = "0.8", features = ["v4"] }
num-rational = "*"
log = "~0.4"
log4rs = "*"

#[dependencies.cursive]
#version = "*"
#default-features = false
#features = ["termion-backend"]