# https://github.com/altercation/solarized

shadow = true
borders = "simple"

[colors]
background = "#002b36"          # base03
view = "#002b36"                # base03
shadow = "#073642"              # base02

primary = "#839496"             # base0
secondary = "#93a1a1"           # base1
tertiary = "#eee8d5"            # base2

title_primary = "#268bd2"        # blue
title_secondary = "#2aa198"      # cyan

highlight = "#eee8d5"            # base2
highlight_inactive = "#93a1a1"   # base1
highlight_text = "#dc322f"       # red

yellow =  "#b58900"
orange =  "#cb4b16"
red =     "#dc322f"
magenta = "#d33682"
violet =  "#6c71c4"
blue =    "#268bd2"
cyan =    "#2aa198"
green =   "#859900"